# Generated by Django 5.0.6 on 2024-07-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='product_ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderitem'),
        ),
    ]
