# Generated by Django 5.0.6 on 2024-07-26 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_shippingaddress_product_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='product_ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderitem'),
        ),
    ]
